### ISSUE TITLE
rewrite using hypercore-index

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/hyperdrive-stats#13]
https://github.com/juliangruber/hypercore-index

-> persistence, more events

**Comment by pfrazee** [comment]
It looks like this is under way in master, is it in a good usable state? (I could use this repo rn.)

**Comment by juliangruber** [comment]
@pfrazee those stats work for sure, I designed the implementation together with @mafintosh: https://github.com/juliangruber/hyperdrive-stats/blob/master/index.js#L24-L27

is that good enough for you rn?

**Comment by pfrazee** [comment]
Yeah I can make any PRs I need, I just wanted to know if we're in a stable place.

**Comment by juliangruber** [comment]
ah ok, yeah I definitely think so :) Closing then for now
