### ISSUE TITLE
Should we not persist upload/download rates?

### ISSUE THREAD

**Issue by joehand** [juliangruber/hyperdrive-stats#22]
It seems weird to persist the upload and download rate stats. These don't mean anything in the database, only with an active connection.

Is it worth taking these out of the database?

**Comment by yoshuawuyts** [comment]
This sounds reasonable

**Comment by joehand** [comment]
Made a module to do this! https://github.com/joehand/hyperdrive-network-speed

We could put this in hyperdrive-stats if we still want all the stats in one place.
