### ISSUE TITLE
Zero out transfer speeds when not actively transferring

### ISSUE THREAD

**Issue by joehand** [juliangruber/hyperdrive-stats#23]
(may be related to #22)

Transfer speeds stay at a value, even after transfer finished or connection is lost. We should zero the speeds out if not actively uploading/downloading.

The way we did it [previously in the CLI](https://github.com/datproject/dat/blob/master/commands/download.js#L63) will not really work here but I can think about it a bit more.

**Comment by juliangruber** [comment]
what about something like this?

```js
setInterval(() => {
  bps = speed(0)
}, 1000)
```

this way the speedometer is updated _at least_ once a second.

**Comment by joehand** [comment]
Since speeds were removed for #22 we can close this. Unless you were thinking to put them back in later?
