### ISSUE TITLE
stat: bytesTotal

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/hyperdrive-stats#3]
``` js
const update = () => {  stats.bytesTotal = archive.content.bytes }
archive.open(update)
archive.on('download', update)
```

**Comment by juliangruber** [comment]
could also use `archive.list()` instead of `archive.on('download')` for further updates, so it works when you're the author of the archive and thus don't download anything

**Comment by joehand** [comment]
What about using `archive.metadata.on('update')`? Should work for both sharing and downloads. I can't remember if this is called on init though.
