### ISSUE TITLE
stat: blocksProgress

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/hyperdrive-stats#6]
``` js
archive.list().on('data', entry => {
  if (archive.isEntryDownloaded(entry)) stats.blocksProgress += entry.blocks
})
```

**Comment by juliangruber** [comment]
^ this is not exact as even when an entry isn't fully downloaded yet, the blocks that have already been should count too, right?

**Comment by joehand** [comment]
> ^ this is not exact as even when an entry isn't fully downloaded yet, the blocks that have already been should count too, right?

Yep. We shouldn't rely on `archive.list` to do progress alone. The [latest implementation](https://github.com/joehand/dat-js/pull/11/files) I have in dat-js seems to be working well:

On start, you list files and get initial progress:

``` js
archive.list().on('data', entry => {
  self.stats.blocksProgress += archive.countDownloadedBlocks(entry)
})
```

On download you add block progress:

``` js
archive.on('download', data => {
  self.stats.blocksProgress++
})
```
